% setup paths
addpath(genpath('minFunc'))
addpath(genpath('DP'))
addpath(genpath('bayesian'))
addpath(genpath('bspline_tools'))
addpath(genpath('basis'))
addpath(genpath('data'))
addpath(genpath('gropt'))
addpath(genpath('mlogit_warp'))
addpath(genpath('util'))