function MyMex(filename)
addpath(genpath(pwd));
if(nargin == 0)
    filename = 'ElasticCurvesReparam';
end

if ispc
    lapacklib = fullfile(matlabroot,'extern','lib',computer('arch'),'microsoft',...
        'libmwlapack.lib');
    blaslib = fullfile(matlabroot,'extern','lib',computer('arch'),'microsoft',...
        'libmwblas.lib');
    if isempty(lapacklib)
        lapacklib = fullfile(matlabroot,'extern','lib',computer('arch'),'mingw64',...
            'libmwlapack.lib');
        blaslib = fullfile(matlabroot,'extern','lib',computer('arch'),'mingw64',...
            'libmwblas.lib');
    end
    
    mex('-I./', ...
        '-I./BinaryFiles/', ...
        '-I./Julia/', ...
        '-I./Julia/useless/', ...
        '-I./Manifolds/', ...
        '-I./Manifolds/CFixedRank2Factors/', ...
        '-I./Manifolds/CpxNStQOrth/', ...
        '-I./Manifolds/ElasticShape/', ...
        '-I./Manifolds/EucPositive/', ...
        '-I./Manifolds/Euclidean/', ...
        '-I./Manifolds/Grassmann/', ...
        '-I./Manifolds/L2Sphere/', ...
        '-I./Manifolds/LowRank/', ...
        '-I./Manifolds/Oblique/', ...
        '-I./Manifolds/OrthGroup/', ...
        '-I./Manifolds/PreShapeCurves/', ...
        '-I./Manifolds/SPDManifold/', ...
        '-I./Manifolds/SPDTensor/', ...
        '-I./Manifolds/Sphere/', ...
        '-I./Manifolds/SphereTx/', ...
        '-I./Manifolds/Stiefel/', ...
        '-I./Others/', ...
        '-I./Others/SparseBLAS/', ...
        '-I./Others/fftw/', ...
        '-I./Others/wavelet/', ...
        '-I./Problems/', ...
        '-I./Problems/CFR2BlindDecon2D/', ...
        '-I./Problems/CFR2BlindDeconvolution/', ...
        '-I./Problems/CSOPhaseRetrieval/', ...
        '-I./Problems/ElasticCurvesRO/', ...
        '-I./Problems/EucBlindDeconvolution/', ...
        '-I./Problems/EucFrechetMean/', ...
        '-I./Problems/EucPosSpCd/', ...
        '-I./Problems/EucQuadratic/', ...
        '-I./Problems/GrassRQ/', ...
        '-I./Problems/KarcherMean/', ...
        '-I./Problems/LRBlindDeconvolution/', ...
        '-I./Problems/LRMatrixCompletion/', ...
        '-I./Problems/ObliqueSparsePCA/', ...
        '-I./Problems/ObliqueTestSparsePCA/', ...
        '-I./Problems/OrthBoundingBox/', ...
        '-I./Problems/PreShapePathStraighten/', ...
        '-I./Problems/SPDMean/', ...
        '-I./Problems/SPDTensorDL/', ...
        '-I./Problems/ShapePathStraighten/', ...
        '-I./Problems/SphereConvexHull/', ...
        '-I./Problems/SphereSparsestVector/', ...
        '-I./Problems/SphereTxRQ/', ...
        '-I./Problems/StieBrockett/', ...
        '-I./Problems/StieSoftICA/', ...
        '-I./Problems/StieSparseBrockett/', ...
        '-I./Problems/StieSumBrockett/', ...
        '-I./Problems/WeightedLowrank/', ...
        '-I./Solvers/', ...
        '-I./cwrapper/', ...
        '-I./cwrapper/blas/', ...
        '-I./cwrapper/lapack/', ...
        '-I./test/', ...
        ['./test/' filename '.cpp'], ...
        './Manifolds/Element.cpp', './Manifolds/LinearOPE.cpp', './Manifolds/Manifold.cpp', './Manifolds/ProductElement.cpp', './Manifolds/ProductManifold.cpp', './Manifolds/SharedSpace.cpp', './Manifolds/SmartSpace.cpp', ...
        './Manifolds/CFixedRank2Factors/CFR2Variable.cpp', './Manifolds/CFixedRank2Factors/CFR2Vector.cpp', './Manifolds/CFixedRank2Factors/CFixedRank2Factors.cpp', ...
        './Manifolds/CpxNStQOrth/CSOVariable.cpp', './Manifolds/CpxNStQOrth/CSOVector.cpp', './Manifolds/CpxNStQOrth/CpxNStQOrth.cpp', ...
        './Manifolds/ElasticShape/ElasticShape.cpp', './Manifolds/ElasticShape/ShapeVariable.cpp', './Manifolds/ElasticShape/ShapeVector.cpp', ...
        './Manifolds/EucPositive/EucPosVariable.cpp', './Manifolds/EucPositive/EucPosVector.cpp', './Manifolds/EucPositive/EucPositive.cpp', ...
        './Manifolds/Euclidean/EucVariable.cpp', './Manifolds/Euclidean/EucVector.cpp', './Manifolds/Euclidean/Euclidean.cpp', ...
        './Manifolds/Grassmann/GrassVariable.cpp', './Manifolds/Grassmann/GrassVector.cpp', './Manifolds/Grassmann/Grassmann.cpp', ...
        './Manifolds/L2Sphere/L2Sphere.cpp', './Manifolds/L2Sphere/L2SphereVariable.cpp', './Manifolds/L2Sphere/L2SphereVector.cpp', ...
        './Manifolds/LowRank/LowRank.cpp', './Manifolds/LowRank/LowRankVariable.cpp', './Manifolds/LowRank/LowRankVector.cpp', ...
        './Manifolds/Oblique/Oblique.cpp', './Manifolds/Oblique/ObliqueVariable.cpp', './Manifolds/Oblique/ObliqueVector.cpp', ...
        './Manifolds/OrthGroup/OrthGroup.cpp', './Manifolds/OrthGroup/OrthGroupVariable.cpp', './Manifolds/OrthGroup/OrthGroupVector.cpp', ...
        './Manifolds/PreShapeCurves/PSCVariable.cpp', './Manifolds/PreShapeCurves/PSCVector.cpp', './Manifolds/PreShapeCurves/PreShapeCurves.cpp', ...
        './Manifolds/SPDManifold/SPDManifold.cpp', './Manifolds/SPDManifold/SPDVariable.cpp', './Manifolds/SPDManifold/SPDVector.cpp', ...
        './Manifolds/SPDTensor/SPDTVariable.cpp', './Manifolds/SPDTensor/SPDTVector.cpp', './Manifolds/SPDTensor/SPDTensor.cpp', ...
        './Manifolds/Sphere/Sphere.cpp', './Manifolds/Sphere/SphereVariable.cpp', './Manifolds/Sphere/SphereVector.cpp', ...
        './Manifolds/SphereTx/SphereTx.cpp', ...
        './Manifolds/Stiefel/StieVariable.cpp', './Manifolds/Stiefel/StieVector.cpp', './Manifolds/Stiefel/Stiefel.cpp', ...
        './Others/ForDebug.cpp', './Others/MinPNormConHull.cpp', './Others/MyMatrix.cpp', './Others/Spline.cpp', './Others/Timer.cpp', './Others/randgen.cpp', ...
        './Others/SparseBLAS/nist_spblas.cpp', ...
        './Others/wavelet/wavelet.cpp', ...
        './Problems/Problem.cpp', './Problems/juliaProblem.cpp', './Problems/mexProblem.cpp', ...
        './Problems/ElasticCurvesRO/DriverElasticCurvesRO.cpp', './Problems/ElasticCurvesRO/ElasticCurvesRO.cpp', ...
        './Problems/EucFrechetMean/EucFrechetMean.cpp', ...
        './Problems/PreShapePathStraighten/PreShapePathStraighten.cpp', ...
        './Problems/SphereConvexHull/SphereConvexHull.cpp', ...
        './Solvers/LRBFGS.cpp', './Solvers/LRBFGSLPSub.cpp', './Solvers/LRTRSR1.cpp', './Solvers/MRankAdaptive.cpp', './Solvers/QuasiNewton.cpp', './Solvers/RBFGS.cpp', './Solvers/RBFGSLPSub.cpp', './Solvers/RBroydenFamily.cpp', './Solvers/RCG.cpp', './Solvers/RGS.cpp', './Solvers/RNewton.cpp', './Solvers/RSD.cpp', './Solvers/RTRNewton.cpp', './Solvers/RTRSD.cpp', './Solvers/RTRSR1.cpp', './Solvers/RWRBFGS.cpp', './Solvers/Solvers.cpp', './Solvers/SolversLS.cpp', './Solvers/SolversLSLPSub.cpp', './Solvers/SolversTR.cpp', ...
        '-DROPTLIB_WITH_FFTW', '-L./BinaryFiles/', blaslib, lapacklib, '-largeArrayDims', '-output', ['./BinaryFiles/' filename ]);
    
else
    mex('-I./', ...
        '-I./BinaryFiles/', ...
        '-I./Julia/', ...
        '-I./Julia/useless/', ...
        '-I./Manifolds/', ...
        '-I./Manifolds/CFixedRank2Factors/', ...
        '-I./Manifolds/CpxNStQOrth/', ...
        '-I./Manifolds/ElasticShape/', ...
        '-I./Manifolds/EucPositive/', ...
        '-I./Manifolds/Euclidean/', ...
        '-I./Manifolds/Grassmann/', ...
        '-I./Manifolds/L2Sphere/', ...
        '-I./Manifolds/LowRank/', ...
        '-I./Manifolds/Oblique/', ...
        '-I./Manifolds/OrthGroup/', ...
        '-I./Manifolds/PreShapeCurves/', ...
        '-I./Manifolds/SPDManifold/', ...
        '-I./Manifolds/SPDTensor/', ...
        '-I./Manifolds/Sphere/', ...
        '-I./Manifolds/SphereTx/', ...
        '-I./Manifolds/Stiefel/', ...
        '-I./Others/', ...
        '-I./Others/SparseBLAS/', ...
        '-I./Others/fftw/', ...
        '-I./Others/wavelet/', ...
        '-I./Problems/', ...
        '-I./Problems/CFR2BlindDecon2D/', ...
        '-I./Problems/CFR2BlindDeconvolution/', ...
        '-I./Problems/CSOPhaseRetrieval/', ...
        '-I./Problems/ElasticCurvesRO/', ...
        '-I./Problems/EucBlindDeconvolution/', ...
        '-I./Problems/EucFrechetMean/', ...
        '-I./Problems/EucPosSpCd/', ...
        '-I./Problems/EucQuadratic/', ...
        '-I./Problems/GrassRQ/', ...
        '-I./Problems/KarcherMean/', ...
        '-I./Problems/LRBlindDeconvolution/', ...
        '-I./Problems/LRMatrixCompletion/', ...
        '-I./Problems/ObliqueSparsePCA/', ...
        '-I./Problems/ObliqueTestSparsePCA/', ...
        '-I./Problems/OrthBoundingBox/', ...
        '-I./Problems/PreShapePathStraighten/', ...
        '-I./Problems/SPDMean/', ...
        '-I./Problems/SPDTensorDL/', ...
        '-I./Problems/ShapePathStraighten/', ...
        '-I./Problems/SphereConvexHull/', ...
        '-I./Problems/SphereSparsestVector/', ...
        '-I./Problems/SphereTxRQ/', ...
        '-I./Problems/StieBrockett/', ...
        '-I./Problems/StieSoftICA/', ...
        '-I./Problems/StieSparseBrockett/', ...
        '-I./Problems/StieSumBrockett/', ...
        '-I./Problems/WeightedLowrank/', ...
        '-I./Solvers/', ...
        '-I./cwrapper/', ...
        '-I./cwrapper/blas/', ...
        '-I./cwrapper/lapack/', ...
        '-I./test/', ...
        ['./test/' filename '.cpp'], ...
        './Manifolds/Element.cpp', './Manifolds/LinearOPE.cpp', './Manifolds/Manifold.cpp', './Manifolds/ProductElement.cpp', './Manifolds/ProductManifold.cpp', './Manifolds/SharedSpace.cpp', './Manifolds/SmartSpace.cpp', ...
        './Manifolds/CFixedRank2Factors/CFR2Variable.cpp', './Manifolds/CFixedRank2Factors/CFR2Vector.cpp', './Manifolds/CFixedRank2Factors/CFixedRank2Factors.cpp', ...
        './Manifolds/CpxNStQOrth/CSOVariable.cpp', './Manifolds/CpxNStQOrth/CSOVector.cpp', './Manifolds/CpxNStQOrth/CpxNStQOrth.cpp', ...
        './Manifolds/ElasticShape/ElasticShape.cpp', './Manifolds/ElasticShape/ShapeVariable.cpp', './Manifolds/ElasticShape/ShapeVector.cpp', ...
        './Manifolds/EucPositive/EucPosVariable.cpp', './Manifolds/EucPositive/EucPosVector.cpp', './Manifolds/EucPositive/EucPositive.cpp', ...
        './Manifolds/Euclidean/EucVariable.cpp', './Manifolds/Euclidean/EucVector.cpp', './Manifolds/Euclidean/Euclidean.cpp', ...
        './Manifolds/Grassmann/GrassVariable.cpp', './Manifolds/Grassmann/GrassVector.cpp', './Manifolds/Grassmann/Grassmann.cpp', ...
        './Manifolds/L2Sphere/L2Sphere.cpp', './Manifolds/L2Sphere/L2SphereVariable.cpp', './Manifolds/L2Sphere/L2SphereVector.cpp', ...
        './Manifolds/LowRank/LowRank.cpp', './Manifolds/LowRank/LowRankVariable.cpp', './Manifolds/LowRank/LowRankVector.cpp', ...
        './Manifolds/Oblique/Oblique.cpp', './Manifolds/Oblique/ObliqueVariable.cpp', './Manifolds/Oblique/ObliqueVector.cpp', ...
        './Manifolds/OrthGroup/OrthGroup.cpp', './Manifolds/OrthGroup/OrthGroupVariable.cpp', './Manifolds/OrthGroup/OrthGroupVector.cpp', ...
        './Manifolds/PreShapeCurves/PSCVariable.cpp', './Manifolds/PreShapeCurves/PSCVector.cpp', './Manifolds/PreShapeCurves/PreShapeCurves.cpp', ...
        './Manifolds/SPDManifold/SPDManifold.cpp', './Manifolds/SPDManifold/SPDVariable.cpp', './Manifolds/SPDManifold/SPDVector.cpp', ...
        './Manifolds/SPDTensor/SPDTVariable.cpp', './Manifolds/SPDTensor/SPDTVector.cpp', './Manifolds/SPDTensor/SPDTensor.cpp', ...
        './Manifolds/Sphere/Sphere.cpp', './Manifolds/Sphere/SphereVariable.cpp', './Manifolds/Sphere/SphereVector.cpp', ...
        './Manifolds/SphereTx/SphereTx.cpp', ...
        './Manifolds/Stiefel/StieVariable.cpp', './Manifolds/Stiefel/StieVector.cpp', './Manifolds/Stiefel/Stiefel.cpp', ...
        './Others/ForDebug.cpp', './Others/MinPNormConHull.cpp', './Others/MyMatrix.cpp', './Others/Spline.cpp', './Others/Timer.cpp', './Others/randgen.cpp', ...
        './Others/SparseBLAS/nist_spblas.cpp', ...
        './Others/wavelet/wavelet.cpp', ...
        './Problems/Problem.cpp', './Problems/juliaProblem.cpp', './Problems/mexProblem.cpp', ...
        './Problems/ElasticCurvesRO/DriverElasticCurvesRO.cpp', './Problems/ElasticCurvesRO/ElasticCurvesRO.cpp', ...
        './Problems/EucFrechetMean/EucFrechetMean.cpp', ...
        './Problems/PreShapePathStraighten/PreShapePathStraighten.cpp', ...
        './Problems/SphereConvexHull/SphereConvexHull.cpp', ...
        './Solvers/LRBFGS.cpp', './Solvers/LRBFGSLPSub.cpp', './Solvers/LRTRSR1.cpp', './Solvers/MRankAdaptive.cpp', './Solvers/QuasiNewton.cpp', './Solvers/RBFGS.cpp', './Solvers/RBFGSLPSub.cpp', './Solvers/RBroydenFamily.cpp', './Solvers/RCG.cpp', './Solvers/RGS.cpp', './Solvers/RNewton.cpp', './Solvers/RSD.cpp', './Solvers/RTRNewton.cpp', './Solvers/RTRSD.cpp', './Solvers/RTRSR1.cpp', './Solvers/RWRBFGS.cpp', './Solvers/Solvers.cpp', './Solvers/SolversLS.cpp', './Solvers/SolversLSLPSub.cpp', './Solvers/SolversTR.cpp', ...
        '-DROPTLIB_WITH_FFTW', '-L./BinaryFiles/', '-lmwblas', '-lmwlapack', '-largeArrayDims', '-output', ['./BinaryFiles/' filename ]);
end
end